### ISSUE TITLE
share_of_one is in an odd place

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/raw-ipa#119]
This is currently attached to the `Mesh` interface, which doesn't make a whole lot of sense.  It probably makes more sense to attach this to the `Replicated` interface.

**Comment by akoshelev** [comment]
It is done already in #102 https://github.com/martinthomson/raw-ipa/blob/55039564955e35bc76a03a5addfa1f81911cfb12/src/secret_sharing/replicated.rs#L38
